id: P002909
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 10:27:46.557124
source_metadata:
  id: bdr:W3CN4042
  title: ཚད་མ་བསྡུས་པ་རིགས་པའི་མཚོན་ཆ།
  author: ''
  volumes:
    090f9dd10d7f45369a9360a7966af48f:
      image_group_id: I3CN4206
      title: ''
      volume_number: 1
      total_pages: 382
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
