id: IC433022E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:23:02+00:00'
last_modified: '2022-06-07T16:07:07.237647+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4042
  title: ཚད་མ་བསྡུས་པ་རིགས་པའི་མཚོན་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8DBC:
      image_group_id: I3CN4206
      title: ''
      total_pages: 382
      order: 1
      base_file: 8DBC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
